#!/usr/bin/env php
<?php

if (PHP_VERSION_ID < 70000) {
    file_put_contents('php://stderr', sprintf(
        "The project requires PHP 7.0 version or higher and your system has\n".
        "PHP %s version installed.\n\n".
        PHP_VERSION
    ));
    exit(1);
}

require file_exists(__DIR__ . '/../../autoload.php')
    ? __DIR__ . '/../../autoload.php'
    : __DIR__ . '/vendor/autoload.php'
;

$version = '1.0.0';
// Windows uses Path instead of PATH
if (!isset($_SERVER['PATH']) && isset($_SERVER['Path'])) {
    $_SERVER['PATH'] = $_SERVER['Path'];
}

// DB
require __DIR__.'/src/db/console.php';

$app = new Symfony\Component\Console\Application('Zank Command Tool', $version);
$app->add(new Zank\Console\TableImportCommand);
$app->add(new Zank\Console\TableOutCommand);
$app->setDefaultCommand('list');
$app->run();