#!/usr/bin/env php
<?php

if (PHP_VERSION_ID < 70000) {
    file_put_contents('php://stderr', sprintf(
        "The project requires PHP 7.0 version or higher and your system has\n".
        "PHP %s version installed.\n\n".
        PHP_VERSION
    ));
    exit(1);
}

// Windows uses Path instead of PATH
if (!isset($_SERVER['PATH']) && isset($_SERVER['Path'])) {
    $_SERVER['PATH'] = $_SERVER['Path'];
}

require __DIR__.'/bootstrap.php';
