#!/usr/bin/env php
<?php
if (PHP_VERSION_ID < 50500) {
    file_put_contents('php://stderr', sprintf(
        "ThinkSNS Installer requires PHP 5.5 version or higher and your system has\n".
        "PHP %s version installed.\n\n".
        "To solve this issue, upgrade your PHP installation or install ThinkSNS manually\n".
        "executing the following command:\n\n".
        "composer create-project medz/thinksns-4 <project-name> <thinksns-version>\n\n",
        PHP_VERSION
    ));
    exit(1);
}

require file_exists(__DIR__ . '/../../autoload.php')
    ? __DIR__ . '/../../autoload.php'
    : __DIR__ . '/vendor/autoload.php'
;

$version = '1.0.0';
// Windows uses Path instead of PATH
if (!isset($_SERVER['PATH']) && isset($_SERVER['Path'])) {
    $_SERVER['PATH'] = $_SERVER['Path'];
}

// DB
require __DIR__.'/src/db/console.php';

$app = new Symfony\Component\Console\Application('Zank Command Tool', $version);
$app->add(new Zank\Console\TableImportCommand);
$app->setDefaultCommand('list');
$app->run();